#%RAML 1.0 ResourceType

#This file is located at resourceTypes/subSystemResource.raml


get:   
  responses: 
    200:
      body:
        application/json:
          type: <<customeResourceType>>[]
            

  