#%RAML 1.0 DataType

#This file is located at dataTypes/ClinicalImpression.raml

type: object
properties: 
  MEDICAL_RECORD_NUMBER?: string
  CSN_ID?: string
  NOTE_TIME?: string
  NOTE_SIGNED_BY?: string
  NOTE_TYPE?: string
  NOTE_CATEGORY?: string
  NOTE_ID?: string
  PURPOSE?: string
  NOTE_TEXT?: string
  NOTE_TEXT_LINE?: string